services:
  echo-server:
    extends:
      file: ../compose-security-baseline/hardening.yml
      service: hardened-small
    image: ghcr.io/enucatl/echo-server:master
    build:
      context: ./build/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "12001:4001/udp"
      - "13001:5001"
    networks:
      - default
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0


networks:
  default:
    enable_ipv6: true
    driver_opts:
      com.docker.network.endpoint.sysctls: '{"net.ipv6.conf.eth0.proxy_ndp": "1"}'
    ipam:
      driver: default
