version: '3.8'

services:
  echo-server:
    image: ghcr.io/enucatl/echo-server:master
    build:
      context: ./build/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4001:4001/udp"
      - "5001:5001"


networks:
  default:
    enable_ipv6: true
