name: build from source

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yaml
      - build/*
  pull_request:
    paths:
      - .github/workflows/build.yaml
      - build/*

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
    uses: Enucatl/docker-compose-security-baseline/.github/workflows/docker-ci.yml@main
    with:
      image_name: ghcr.io/enucatl/echo-server
      context: ./build
      dockerfile: Dockerfile
      platforms: linux/amd64
      push: ${{ github.event_name != 'pull_request' }}
      fail_on_fs_findings: false
      fail_on_image_findings: false
    secrets: inherit
